### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wrxhardworking** [HalcyonAzure/CS144#1]
博主能给出lab的课程地址和文档地址吗

**Comment by HalcyonAzure** [comment]
我这个`repo`里面包含的是`2021`年斯坦福计算机网络那个课的，现在[官方公开](https://cs144.github.io)的只有`2023`还没有结课的文档，如果你是要看`2021`的实验文档的话[这里](https://github.com/HalcyonAzure/CS144/tree/master/assignments)就是，我写这个实验的话没有看配套的课程，是学校上完了计算机网络的课以后直接看实验要求的文档然后写的。如果要看原本的配套课程的话可以看看B站搬运的：[BV137411Z7LR](https://www.bilibili.com/video/BV137411Z7LR)

**Comment by wrxhardworking** [comment]
好的 谢谢博主

**Comment by HalcyonAzure** [comment]
那我就把这个`issues`给关掉了，后面遇到啥问题也可以留言XD
